### model
model_name_or_path: your_llama3_model_path

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: ./examples/deepspeed/ds_z3_config.json

### dataset
dataset: your_dataset_name
dataset_dir: your_dataset_dir
template: alpaca
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: your_output_dir
logging_steps: 1
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
weight_decay: 0.0
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000